import { useState, useEffect } from 'react'
import {
  Box,
  Container,
  Paper,
  Typography,
  Grid,
  Card,
  CardContent,
  Chip,
  Avatar,
  Stack,
  Alert
} from '@mui/material'
import TableRestaurantIcon from '@mui/icons-material/TableRestaurant'
import Navbar from './Navbar'

function TableAssignment() {
  const [assignments, setAssignments] = useState([])

  useEffect(() => {
    // This would typically load actual table assignments
    // For now, show a placeholder
    setAssignments([
      {
        table: 'Table 1',
        time: '6:00 PM',
        date: '2024-01-15',
        members: [
          { name: 'John Doe', type: 'Reflective Introvert' },
          { name: 'Jane Smith', type: 'Thoughtful Conversationalist' }
        ]
      }
    ])
  }, [])

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', pb: 8 }}>
      <Navbar />

      <Container maxWidth="lg" sx={{ pt: '100px' }}>
        <Box sx={{ mb: 4, textAlign: 'center' }}>
          <Typography variant="h3" component="h1" gutterBottom color="primary">
            Table Assignments
          </Typography>
          <Typography variant="body1" color="text.secondary">
            Current table assignments for upcoming dining experiences.
          </Typography>
        </Box>

        <Grid container spacing={4}>
          {assignments.map((assignment, index) => (
            <Grid size={{ xs: 12, md: 6, lg: 4 }} key={index}>
              <Card elevation={2}>
                <CardContent>
                  <Stack direction="row" spacing={2} alignItems="center" sx={{ mb: 2 }}>
                    <Avatar sx={{ bgcolor: 'primary.main' }}>
                      <TableRestaurantIcon />
                    </Avatar>
                    <Typography variant="h5">
                      {assignment.table}
                    </Typography>
                  </Stack>

                  <Typography variant="body2" color="text.secondary" gutterBottom>
                    <strong>Date:</strong> {new Date(assignment.date).toLocaleDateString()}
                  </Typography>
                  <Typography variant="body2" color="text.secondary" gutterBottom>
                    <strong>Time:</strong> {assignment.time}
                  </Typography>

                  <Typography variant="subtitle1" sx={{ mt: 2, mb: 1, fontWeight: 'bold' }}>
                    Table Members:
                  </Typography>

                  <Stack spacing={1}>
                    {assignment.members.map((member, idx) => (
                      <Paper key={idx} variant="outlined" sx={{ p: 1, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <Typography variant="body2">{member.name}</Typography>
                        <Chip label={member.type} size="small" color="secondary" variant="outlined" />
                      </Paper>
                    ))}
                  </Stack>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>

        <Alert severity="info" sx={{ mt: 6 }}>
          <strong>Demo Mode:</strong> This page would show actual table assignments
          generated by the admin dashboard in a live system.
        </Alert>

      </Container>
    </Box>
  )
}

export default TableAssignment
