import { useState, useEffect } from 'react'
import Navbar from './Navbar'

function TableAssignment() {
  const [assignments, setAssignments] = useState([])

  useEffect(() => {
    // This would typically load actual table assignments
    // For now, show a placeholder
    setAssignments([
      {
        table: 'Table 1',
        time: '6:00 PM',
        date: '2024-01-15',
        members: [
          { name: 'John Doe', type: 'Reflective Introvert' },
          { name: 'Jane Smith', type: 'Thoughtful Conversationalist' }
        ]
      }
    ])
  }, [])

  return (
    <div className="table-assignment-page">
      <header className="page-header">
        <Navbar />
      </header>

      <main className="assignment-main">
        <div className="container">
          <h1>Table Assignments</h1>
          <p>Current table assignments for upcoming dining experiences.</p>

          <div className="assignments-container">
            {assignments.map((assignment, index) => (
              <div key={index} className="assignment-card">
                <h3>{assignment.table}</h3>
                <p><strong>Date:</strong> {new Date(assignment.date).toLocaleDateString()}</p>
                <p><strong>Time:</strong> {assignment.time}</p>
                
                <div className="members-list">
                  <h4>Table Members:</h4>
                  {assignment.members.map((member, idx) => (
                    <div key={idx} className="member">
                      <span className="name">{member.name}</span>
                      <span className="type">{member.type}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="demo-notice">
            <p>
              <strong>Demo Mode:</strong> This page would show actual table assignments 
              generated by the admin dashboard in a live system.
            </p>
          </div>
        </div>
      </main>
    </div>
  )
}

export default TableAssignment